<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Барные стулья бара  пластика  хрома купить дизайнерские деревянные");
$APPLICATION->SetPageProperty("description", "Барные стулья от компании Дизайн Станция - Мебель для кафе, баров и ресторанов.");
$APPLICATION->SetTitle("Барные стулья для бара из пластика и хрома | Купить дизайнерские деревянные барные стулья для бара");
?> <?$APPLICATION->IncludeComponent("bitrix:catalog", "intels", array(
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "1",
	"HIDE_NOT_AVAILABLE" => "N",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalog/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "N",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "Y",
	"CACHE_GROUPS" => "N",
	"SET_STATUS_404" => "Y",
	"SET_TITLE" => "Y",
	"ADD_SECTIONS_CHAIN" => "Y",
	"ADD_ELEMENT_CHAIN" => "N",
	"USE_ELEMENT_COUNTER" => "Y",
	"USE_FILTER" => "Y",
	"FILTER_NAME" => "",
	"FILTER_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PRICE_CODE" => array(
	),
	"USE_REVIEW" => "N",
	"USE_COMPARE" => "N",
	"PRICE_CODE" => array(
		0 => "BASE",
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "N",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"CONVERT_CURRENCY" => "N",
	"BASKET_URL" => "/basket/index.php",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "ELEMENT_ID",
	"USE_PRODUCT_QUANTITY" => "Y",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"ADD_PROPERTIES_TO_BASKET" => "Y",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"PARTIAL_PRODUCT_PROPERTIES" => "N",
	"PRODUCT_PROPERTIES" => array(
		0 => "COLORS",
	),
	"SHOW_TOP_ELEMENTS" => "N",
	"SECTION_COUNT_ELEMENTS" => "Y",
	"SECTION_TOP_DEPTH" => "1",
	"PAGE_ELEMENT_COUNT" => "10000",
	"LINE_ELEMENT_COUNT" => "",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "asc",
	"ELEMENT_SORT_FIELD2" => "name",
	"ELEMENT_SORT_ORDER2" => "asc",
	"LIST_PROPERTY_CODE" => array(
		0 => "NEW_YEAR",
		1 => "COLORS",
		2 => "ON_SALE",
		3 => "LIDER_OF_SALES",
		4 => "NOVELTY",
		5 => "",
	),
	"INCLUDE_SUBSECTIONS" => "A",
	"LIST_META_KEYWORDS" => "UF_CATEGORY_METATEGS",
	"LIST_META_DESCRIPTION" => "UF_CATEGORY_METADESC",
	"LIST_BROWSER_TITLE" => "UF_CATEGORY_TITLE",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "CHAR_WIDTH",
		1 => "DEPTH",
		2 => "CHAR_HEIGHT",
		3 => "RIDE_HEIGHT",
		4 => "BASE_SIZE",
		5 => "REC_SIZE_TT",
		6 => "FRAME_COLOR",
		7 => "SIDENIE",
		8 => "CHAR_WEIGHT",
		9 => "CHAR_MANUFACTURER",
		10 => "CHAR_MATERIAL",
		11 => "MARKS",
		12 => "IND_SIZE",
		13 => "COLORS",
		14 => "POSTAVKA",
		15 => "CHAR_LENGTH",
		16 => "CHAR_SEAT",
		17 => "CHAR_FOUNDATION_MATERIAL",
		18 => "CHAR_MECH",
		19 => "CHAR_DURABILITY",
		20 => "STOLESHNICA",
		21 => "ON_SALE",
		22 => "LIDER_OF_SALES",
		23 => "NOVELTY",
		24 => "",
	),
	"DETAIL_META_KEYWORDS" => "PAGE_METATEGS",
	"DETAIL_META_DESCRIPTION" => "PAGE_METADESCR",
	"DETAIL_BROWSER_TITLE" => "PAGE_TITLE",
	"LINK_IBLOCK_TYPE" => "",
	"LINK_IBLOCK_ID" => "",
	"LINK_PROPERTY_SID" => "",
	"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
	"USE_ALSO_BUY" => "N",
	"USE_STORE" => "N",
	"PAGER_TEMPLATE" => "",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "N",
	"PAGER_TITLE" => "Товары",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "N",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_ID#/",
		"element" => "#SECTION_ID#/#ELEMENT_ID#/",
		"compare" => "compare.php?action=#ACTION_CODE#",
	),
	"VARIABLE_ALIASES" => array(
		"compare" => array(
			"ACTION_CODE" => "action",
		),
	)
	),
	false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>